### PR TITLE
Fixed newlines issue, and updated dependencies

### PR DESCRIPTION
**Pull request by tom-lord**
What do you think I should do with this gem, in the long-term? I.e. should I just make a Com Laude fork and use that as our project dependency?

### CODE REVIEW

**Comment by tom-lord** [comment]
This fixes issue vs-305, raised in March 2015 hahaha :+1:

**Comment by tom-lord** [comment]
I've merged for my own convenience, but I cannot release a gem obviously.

**Comment by equivalent** [comment]
I can transfer the ownership to you  if you want :)

**Comment by equivalent** [comment]
added @tom-lord  as official owner list of gem Witch Doctor   https://rubygems.org/gems/witch_doctor

Lord help us all  !! :pray:

**Pull request merged**
